# Generated by Django 5.2.3 on 2025-06-30 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_complaint_location_alter_complaint_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='complaint',
            name='Please make sure that  you have enter the location ',
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(('region__isnull', True), ('location__isnull', True), _negated=True), name='region_or_location_required'),
        ),
    ]
