# Generated by Django 5.2.3 on 2025-06-30 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_complaint_please_make_sure_that_you_have_enter_the_location__and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='complaint',
            name='region_or_location_required',
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.UniqueConstraint(condition=models.Q(('region__isnull', False), ('location__isnull', False)), fields=('region', 'location'), name='unique_region_location'),
        ),
    ]
