# Generated by Django 5.2.3 on 2025-06-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_complaint_region_or_location_required_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='complaint',
            name='unique_region_location',
        ),
    ]
