# Generated by Django 5.2.3 on 2025-06-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block_name',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='flate_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='floor_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
