# Generated by Django 5.2.3 on 2025-06-27 06:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_address_profile_permanant_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FamilyMembers',
            new_name='FamilyMember',
        ),
    ]
