# Generated by Django 5.2.3 on 2025-06-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_familymembers_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('R', 'Resident'), ('SP', 'ServicePerson'), ('S', 'Staff')], default='R', max_length=2),
        ),
    ]
