# Generated by Django 5.2.3 on 2025-06-27 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_of_experience', models.IntegerField()),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('user_role', models.CharField(choices=[('R', 'Resident'), ('SP', 'ServicePerson'), ('S', 'Staff')], default='R', max_length=2)),
                ('location', models.CharField(max_length=200)),
                ('working_time', models.CharField(max_length=50)),
                ('total_year_experience', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(related_name='service_persons', to='accounts.services')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
