# Generated by Django 5.2.3 on 2025-06-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_services_servicepersonprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=23222323, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='resident/images'),
        ),
        migrations.AddField(
            model_name='servicepersonprofile',
            name='phone',
            field=models.CharField(default=2323232323, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepersonprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='serviceman/images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='year_of_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
