# Generated by Django 5.2.3 on 2025-06-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_phone_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepersonprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
