# Generated by Django 5.2.3 on 2025-06-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_created_at_profile_update_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='servicepersonprofile',
            name='services',
        ),
        migrations.RemoveField(
            model_name='servicepersonprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='ServicePersonProfile',
        ),
    ]
