# Generated by Django 5.2.3 on 2025-06-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('phone', models.CharField(max_length=12)),
                ('user_role', models.CharField(choices=[('CI', 'Citizens'), ('OF', 'Officer'), ('MA', 'Manager'), ('A', 'Admin')], default='CI', max_length=2)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='resident/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
