# Generated by Django 5.2.3 on 2025-06-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(default=3343, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='your adhar number '),
        ),
    ]
