# Generated by Django 5.2.3 on 2025-06-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_zip_code_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='your adhar number '),
        ),
    ]
